sudo: false
language: python
cache: pip
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install psycopg2
  - pip install codecov
  - pip install -e .
script:
  - py.test --cov=flask_dance
after_success:
  - codecov
